development:
  adapter: postgresql
  encoding: unicode
  database: pgdb
  pool: 5
  username: rahilla
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: pbdg
  pool: 5
  username: rahilla
  password:
