# development:
#   adapter: postgresql
#   encoding: unicode
#   database: pgdb
#   pool: 5
#   username: rahillazafar
#   password:

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: pbdg
#   pool: 5
#   username: rahillazafar
#   password:
    development:
      adapter: sqlite3
      database: db/development.sqlite3
      pool: 5
      timeout: 5000

    test:
      adapter: sqlite3
      database: db/test.sqlite3
      pool: 5
      timeout: 5000


